name: APK

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        java-version: '1.8'
    - name: Build
      run: |
        ./gradlew assemble
    - name: Store generated APK file
      uses: actions/upload-artifact@v3
      with:
        name: lfgit-app
        path: ./app/build/outputs/apk/debug/app.apk
